version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password  --region us-east-1	 | docker login --username AWS  --password-stdin $REPO_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "commit hash is $COMMIT_HASH"
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image
      - docker build --build-arg REVISION=$COMMIT_HASH --build-arg ENVI=$ENVS -t $REPO_URL:latest .
      - docker tag $REPO_URL:latest $REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images.
      - docker push $REPO_URL:latest
      - docker push $REPO_URL:$IMAGE_TAG
